name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Setup Chrome (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      uses: browser-actions/setup-chrome@v1

    - name: Build with Maven
      run: mvn -B clean compile

    - name: Run Selenium Tests
      run: mvn test

    - name: Generate Surefire Report
      if: always()
      run: mvn site -DgenerateReports=false

    - name: Upload Surefire Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-${{ matrix.os }}
        path: target/site

    - name: Send Slack notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: test-automation
        SLACK_TITLE: "🧪 Luma Test Results - ${{ matrix.os }}"
        SLACK_MESSAGE: "${{ job.status == 'success' && '✅ Amalitech will not kill me this year!' || '❌ Some tests failed!' }}"
        SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
        SLACK_FOOTER: "Automated Selenium Test Results"
        SLACK_USERNAME: "GitHub Actions"
        SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

    - name: Send email notification

      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.EMAIL_SENDER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Luma Test Results - ${{ matrix.os }} - ${{ job.status }}
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: Luma Test Automation
        body: |
          Selenium Test Results for Luma E-Commerce Application

          OS: ${{ matrix.os }}
          Status: ${{ job.status }}

          Check the results on GitHub: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

